version: "3.5"

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: maychila1
      POSTGRES_DB: perfume
    ports:
      - 5433:5432
    networks:
      - perfume-service
    restart: always

  frontend-service:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend-service-container
    stdin_open: true
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend-service
    networks:
      - perfume-service

  backend-service:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend-service-container
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/perfume
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=maychila1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - perfume-service
networks:
  perfume-service:
    external: true
